# Database settings.
database:

  # the name of your JDBC driver
  driver_class: org.h2.Driver

  # the username
  user:

  password:

  # the JDBC URL
  url: jdbc:h2:userrest

# server settings
server:
  application_connectors:
    - type: http
      port: 8888

  admin_connectors:
    - type: http
      port: 8889

endpoint: http://localhost:8888/
